from src.nidcpower.Power import VoltagePowerSource

if __name__ == '__main__':
    pxi_4110_channel_2 = VoltagePowerSource(resource_name='PXI_4110_1/2', min_voltage=-20, max_voltage=0)
    v_out = pxi_4110_channel_2.output_voltage()
    i_out = pxi_4110_channel_2.output_current()
    p_out = pxi_4110_channel_2.output_power()
    print(f'{v_out:+#.5e} volts, {i_out:+#.5e} amps, {p_out:+#.5e} Watts')

    pxi_4110_channel_2.power_on()
    v_out = pxi_4110_channel_2.output_voltage()
    i_out = pxi_4110_channel_2.output_current()
    p_out = pxi_4110_channel_2.output_power()
    print(f'{v_out:+#.5e} volts, {i_out:+#.5e} amps, {p_out:+#.5e} Watts')
    pxi_4110_channel_2.power_off()

    pxi_4110_channel_2.set_output_voltage(-1)
    pxi_4110_channel_2.power_on()
    v_out = pxi_4110_channel_2.output_voltage()
    i_out = pxi_4110_channel_2.output_current()
    p_out = pxi_4110_channel_2.output_power()
    print(f'{v_out:+#.5e} volts, {i_out:+#.5e} amps, {p_out:+#.5e} Watts')
    pxi_4110_channel_2.power_off()

    pxi_4110_channel_2.set_output_voltage(-2)
    pxi_4110_channel_2.power_on()
    v_out = pxi_4110_channel_2.output_voltage()
    i_out = pxi_4110_channel_2.output_current()
    p_out = pxi_4110_channel_2.output_power()
    print(f'{v_out:+#.5e} volts, {i_out:+#.5e} amps, {p_out:+#.5e} Watts')
    pxi_4110_channel_2.power_off()

    pxi_4110_channel_2.set_output_voltage(-3)
    pxi_4110_channel_2.set_output_voltage(-4)
    pxi_4110_channel_2.power_on()
    v_out = pxi_4110_channel_2.output_voltage()
    i_out = pxi_4110_channel_2.output_current()
    p_out = pxi_4110_channel_2.output_power()
    print(f'{v_out:+#.5e} volts, {i_out:+#.5e} amps, {p_out:+#.5e} Watts')
    pxi_4110_channel_2.power_off()

    pxi_4110_channel_2.power_on()
    v_out = pxi_4110_channel_2.output_voltage()
    i_out = pxi_4110_channel_2.output_current()
    p_out = pxi_4110_channel_2.output_power()
    print(f'{v_out:+#.5e} volts, {i_out:+#.5e} amps, {p_out:+#.5e} Watts')
    pxi_4110_channel_2.set_output_voltage(-5)
    v_out = pxi_4110_channel_2.output_voltage()
    i_out = pxi_4110_channel_2.output_current()
    p_out = pxi_4110_channel_2.output_power()
    print(f'{v_out:+#.5e} volts, {i_out:+#.5e} amps, {p_out:+#.5e} Watts')
    pxi_4110_channel_2.set_output_voltage(-6)
    v_out = pxi_4110_channel_2.output_voltage()
    i_out = pxi_4110_channel_2.output_current()
    p_out = pxi_4110_channel_2.output_power()
    print(f'{v_out:+#.5e} volts, {i_out:+#.5e} amps, {p_out:+#.5e} Watts')

    pxi_4110_channel_0 = VoltagePowerSource(resource_name='PXI_4110_1/1', min_voltage=0, max_voltage=6)
    v_out = pxi_4110_channel_0.output_voltage()
    i_out = pxi_4110_channel_0.output_current()
    p_out = pxi_4110_channel_0.output_power()
    print(f'{v_out:+#.5e} volts, {i_out:+#.5e} amps, {p_out:+#.5e} Watts')

    pxi_4110_channel_0.power_on()
    v_out = pxi_4110_channel_0.output_voltage()
    i_out = pxi_4110_channel_0.output_current()
    p_out = pxi_4110_channel_0.output_power()
    print(f'{v_out:+#.5e} volts, {i_out:+#.5e} amps, {p_out:+#.5e} Watts')
    pxi_4110_channel_0.power_off()

    pxi_4110_channel_0.set_output_voltage(1)
    pxi_4110_channel_0.power_on()
    v_out = pxi_4110_channel_0.output_voltage()
    i_out = pxi_4110_channel_0.output_current()
    p_out = pxi_4110_channel_0.output_power()
    print(f'{v_out:+#.5e} volts, {i_out:+#.5e} amps, {p_out:+#.5e} Watts')
    pxi_4110_channel_0.power_off()

    pxi_4110_channel_0.set_output_voltage(2)
    pxi_4110_channel_0.power_on()
    v_out = pxi_4110_channel_0.output_voltage()
    i_out = pxi_4110_channel_0.output_current()
    p_out = pxi_4110_channel_0.output_power()
    print(f'{v_out:+#.5e} volts, {i_out:+#.5e} amps, {p_out:+#.5e} Watts')
    pxi_4110_channel_0.power_off()

    pxi_4110_channel_0.set_output_voltage(3)
    pxi_4110_channel_0.set_output_voltage(4)
    pxi_4110_channel_0.power_on()
    v_out = pxi_4110_channel_0.output_voltage()
    i_out = pxi_4110_channel_0.output_current()
    p_out = pxi_4110_channel_0.output_power()
    print(f'{v_out:+#.5e} volts, {i_out:+#.5e} amps, {p_out:+#.5e} Watts')
    pxi_4110_channel_0.power_off()

    pxi_4110_channel_0.power_on()
    v_out = pxi_4110_channel_0.output_voltage()
    i_out = pxi_4110_channel_0.output_current()
    p_out = pxi_4110_channel_0.output_power()
    print(f'{v_out:+#.5e} volts, {i_out:+#.5e} amps, {p_out:+#.5e} Watts')
    pxi_4110_channel_0.set_output_voltage(5)
    v_out = pxi_4110_channel_0.output_voltage()
    i_out = pxi_4110_channel_0.output_current()
    p_out = pxi_4110_channel_0.output_power()
    print(f'{v_out:+#.5e} volts, {i_out:+#.5e} amps, {p_out:+#.5e} Watts')
    pxi_4110_channel_0.set_output_voltage(6)
    v_out = pxi_4110_channel_0.output_voltage()
    i_out = pxi_4110_channel_0.output_current()
    p_out = pxi_4110_channel_0.output_power()
    print(f'{v_out:+#.5e} volts, {i_out:+#.5e} amps, {p_out:+#.5e} Watts')
    pass